### ISSUE TITLE
Grove - 6-Axis Accelerometer&Gyroscope(BMI088) library does not support alternate device address.

### ISSUE THREAD

**Issue by speedbug78** [Seeed-Studio/Grove_6Axis_Accelerometer_And_Gyroscope_BMI088#1]
The default I2C device address is hard coded into this library.  One method is to change the constructor to accept the alternate device address:

In BMI088.cpp:
`BMI088::BMI088( unsigned short acc_addr = BMI088_ACC_ADDRESS, unsigned short gyro_addr = BMI088_GYRO_ADDRESS )
{
    devAddrAcc = acc_addr;
    devAddrGyro = gyro_addr;
}`

remove from BMI088.cpp
`BMI088 bmi088;`

In BMI088.h:
```
#define BMI088_ACC_ALT_ADDRESS      0x18
#define BMI088_GYRO_ALT_ADDRESS         0x68

class BMI088
{
    public:

        BMI088( unsigned short, unsigned short );
```
remove from BMI088.h
`extern BMI088 bmi088;`

This also would drive a minor change to the example BMI088_Example.ino:
`BMI088 bmi088( BMI088_ACC_ADDRESS, BMI088_GYRO_ADDRESS );`

**Comment by PlimptonInnovations** [comment]
I ran into a problem with compiling errors: fixed by adding "(uint_8)" or "(uint_16)" into any "Wire.requestFrom(addr, X)" locations in the .cpp file.

Example of OLD section:
```
uint8_t BMI088::read8(device_type_t dev, uint8_t reg)
{
    uint8_t addr = 0, data = 0;
    
    if(dev) addr = devAddrGyro;
    else addr = devAddrAcc;

    Wire.beginTransmission(addr);
    Wire.write(reg);
    Wire.endTransmission();

    Wire.requestFrom(addr, 1);
    while(Wire.available())
    {
        data = Wire.read();
    }
    
    return data;
```

Example of NEW Section:
```
uint8_t BMI088::read8(device_type_t dev, uint8_t reg)
{
    uint8_t addr = 0, data = 0;
    
    if(dev) addr = devAddrGyro;
    else addr = devAddrAcc;

    Wire.beginTransmission(addr);
    Wire.write(reg);
    Wire.endTransmission();

    Wire.requestFrom(addr, (uint8_t)1);
    while(Wire.available())
    {
        data = Wire.read();
    }
    
    return data;
```

**Comment by ackPeng** [comment]
Thank you very much for your suggestions. The library has been changed accordingly. If you have any questions, please feel free to contact us.
