### ISSUE TITLE
Publish to PlatformIO

### ISSUE THREAD

**Issue by Crazy-Ginger** [Seeed-Studio/Grove_6Axis_Accelerometer_And_Gyroscope_BMI088#2]
Would it be possible to publish this library to PlatformIO's registry?

My team would very much appreciate it.

**Comment by areatrucorp** [comment]
Hi, what is the best way to add this library to my platformio.ini file?

Any advice would be greatly appreciated. Thanks

**Comment by Crazy-Ginger** [comment]
Looks like this is done by adding it to their registry using the CLI. 
[CMD Package Publish](uhttps://docs.platformio.org/en/latest/core/userguide/pkg/cmd_publish.html#cmd-package-publishrl) has a guide on the command to use, but I think it will require a platformIO account

**Comment by ackPeng** [comment]
@Crazy-Ginger  Do you still have this demand now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
